interface EventWordPool {
  name: string;
  words: string[];
}

export const wordPools: Record<string, EventWordPool> = {
  'hari-raya': {
    name: 'Hari Raya 2026',
    words: [
      'Ketupat',
      'Rendang',
      'Lemang',
      'Dodol',
      'Kuih Raya',
      'Baju Raya',
      'Duit Raya',
      'Baju Kurung',
      'Baju Melayu',
      'Songkok',
      'Tudung',
      'Sampin',
      'Pelita',
      'Beduk',
      'Takbir',
      'Aidilfitri',
      'Lebaran',
      'Sahur',
      'Iftar',
      'Ramadan',
      'Kurma',
      'Zakat Fitrah',
      'Silaturrahim',
      'Balik Kampung',
      'Open House',
      'Kuih Tart',
      'Bahulu',
      'Karipap',
      'Seri Muka',
      'Lontong',
      'Bubur Lambuk',
      'Nasi Impit',
      'Satay',
      'Ketupat Palas',
      'Love Letters',
      'Pineapple Tart',
      'Nastar',
      'Masjid',
      'Selawat',
      'Eid Mubarak',
      'Selamat Hari Raya',
      'Maaf Zahir Batin',
      'Baju Raya Baru',
      'Pelita Raya',
      'Kad Raya',
      'Bunga Api',
      'Mercun',
      'Lauk Pauk',
      'Mee Soto',
      'Laksa',
    ],
  },

  'christmas': {
    name: 'Christmas 2026',
    words: [
      'Santa Claus',
      'Christmas Tree',
      'Jingle Bells',
      'Candy Cane',
      'Snowflake',
      'Reindeer',
      'Rudolph',
      'Mistletoe',
      'Eggnog',
      'Stockings',
      'Gingerbread',
      'Wreath',
      'Caroling',
      'Sleigh',
      'North Pole',
      'Elves',
      'Gift Wrap',
      'Ornaments',
      'Angel',
      'Star',
      'Fruitcake',
      'Holly',
      'Snowman',
      'Nutcracker',
      'Turkey',
      'Hot Cocoa',
      'Fireplace',
      'Tinsel',
      'Nativity',
      'Boxing Day',
    ],
  },

  'diwali': {
    name: 'Diwali 2026',
    words: [
      'Diya',
      'Rangoli',
      'Fireworks',
      'Lakshmi',
      'Ganesh',
      'Mithai',
      'Ladoo',
      'Gulab Jamun',
      'Barfi',
      'Halwa',
      'Puja',
      'Lantern',
      'Sari',
      'Kurta',
      'Festive',
      'Prosperity',
      'Gold',
      'Silver',
      'Sparkler',
      'Candle',
      'Flower Garland',
      'Temple',
      'Blessing',
      'Family',
      'New Year',
      'Sweets',
      'Light',
      'Joy',
      'Peace',
      'Celebration',
    ],
  },

  'generic': {
    name: 'Office Bingo',
    words: [
      'Coffee Break',
      'Synergy',
      'Pivot',
      'Deep Dive',
      'Standup',
      'Deadline',
      'Action Item',
      'Bandwidth',
      'Circle Back',
      'Low Hanging Fruit',
      'Touch Base',
      'Leverage',
      'Disruptive',
      'Move the Needle',
      'Pain Point',
      'Ecosystem',
      'Agile',
      'Stakeholder',
      'Deliverable',
      'Milestone',
      'Team Player',
      'Best Practice',
      'Onboarding',
      'KPI',
      'ROI',
      'Brainstorm',
      'Whiteboard',
      'Remote Work',
      'Collaboration',
      'Innovation',
    ],
  },
};

export function getWordPool(slug: string): EventWordPool {
  return wordPools[slug] ?? wordPools['generic'];
}
