interface EventWordPool {
  name: string;
  words: string[];
}

export const wordPools: Record<string, EventWordPool> = {
  'hari-raya': {
    name: 'Hari Raya 2026',
    words: [
      "Rendang Daging",
      "Lemang",
      "Ketupat",
      "Duit Raya",
      "Balik Kampung",
      "Baju Melayu",
      "Baju Kurung",
      "Songkok",
      "Sampin",
      "Pelita",
      "Bunga Api",
      "Rumah Terbuka",
      "Maaf Zahir & Batin",
      "Kuih Raya",
      "Pineapple Tart",
      "Kuih Bangkit",
      "Dodol",
      "Lontong",
      "Serunding",
      "Baju Kebaya",
      "Takbir Raya",
      "Sampul Hijau",
      "Lagu Raya",
      "Ziarah",
      "Sate",
      "Sayur Lodeh",
      "Sambal Kacang",
      "Kuih Makmur",
      "Almond London",
      "Iklan Raya",
      "Bersalaman",
      "Kain Songket",
      "Selendang",
      "Masjid",
      "Bulan Sabit",
      "Lampu Lip Lap",
      "Sirap Bandung",
      "Ketupat Palas",
      "Kuih Semperit",
      "Baju Sedondon"
    ],
  },

  'christmas': {
    name: 'Christmas 2026',
    words: [
      'Santa Claus',
      'Christmas Tree',
      'Jingle Bells',
      'Candy Cane',
      'Snowflake',
      'Reindeer',
      'Rudolph',
      'Mistletoe',
      'Eggnog',
      'Stockings',
      'Gingerbread',
      'Wreath',
      'Caroling',
      'Sleigh',
      'North Pole',
      'Elves',
      'Gift Wrap',
      'Ornaments',
      'Angel',
      'Star',
      'Fruitcake',
      'Holly',
      'Snowman',
      'Nutcracker',
      'Turkey',
      'Hot Cocoa',
      'Fireplace',
      'Tinsel',
      'Nativity',
      'Boxing Day',
    ],
  },

  'diwali': {
    name: 'Diwali 2026',
    words: [
      'Diya',
      'Rangoli',
      'Fireworks',
      'Lakshmi',
      'Ganesh',
      'Mithai',
      'Ladoo',
      'Gulab Jamun',
      'Barfi',
      'Halwa',
      'Puja',
      'Lantern',
      'Sari',
      'Kurta',
      'Festive',
      'Prosperity',
      'Gold',
      'Silver',
      'Sparkler',
      'Candle',
      'Flower Garland',
      'Temple',
      'Blessing',
      'Family',
      'New Year',
      'Sweets',
      'Light',
      'Joy',
      'Peace',
      'Celebration',
    ],
  },

  'generic': {
    name: 'Office Bingo',
    words: [
      'Coffee Break',
      'Synergy',
      'Pivot',
      'Deep Dive',
      'Standup',
      'Deadline',
      'Action Item',
      'Bandwidth',
      'Circle Back',
      'Low Hanging Fruit',
      'Touch Base',
      'Leverage',
      'Disruptive',
      'Move the Needle',
      'Pain Point',
      'Ecosystem',
      'Agile',
      'Stakeholder',
      'Deliverable',
      'Milestone',
      'Team Player',
      'Best Practice',
      'Onboarding',
      'KPI',
      'ROI',
      'Brainstorm',
      'Whiteboard',
      'Remote Work',
      'Collaboration',
      'Innovation',
    ],
  },
};

export function getWordPool(slug: string): EventWordPool {
  return wordPools[slug] ?? wordPools['generic'];
}
